import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window.padding]
  x= 5
  y= 0

[font]
  normal ={ family = "MonoLisia Nerd Font", style = "Regular" }
  size= 11.0

[env]
TERM = "xterm-256color"